name: Build pdf

on:
  pull_request:

permissions:
  contents: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Compile LaTeX document - Template
        uses: dante-ev/latex-action@master
        with:
          working_directory: ./src
          root_file: template.tex
