name: Build pdf

on:
  pull_request:

permissions:
  contents: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Compile LaTeX document - Template
        uses: dante-ev/latex-action@master
        with:
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          root_file: ./src/template.tex
      - name: Compile BibTex - Template
        uses: dante-ev/latex-action@latest
        with:
          compiler: bibtex
          root_file: ./src/template.aux
      - name: Compile LaTeX document - Template
        uses: dante-ev/latex-action@master
        with:
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          root_file: ./src/template.tex