name: Build pdf

on:
  pull_request:

permissions:
  contents: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: src/template.tex
          texlive_version: 2023
          latexmk_shell_escape: true
          args: -pdf -interaction=nonstopmode -output-directory=.build -f
